/**
 * Builds the dashboard's bundled dataset by actually running Parity.
 *
 * Four real reports: each example program before and after the repair loop.
 * The "after" runs use real ledgers — the same decisions the MCP end-to-end
 * test records — so the dashboard shows the loop as it genuinely plays out:
 * DIVERGENT with open findings, then equivalence with every difference either
 * fixed or explicitly accepted.
 */

import { cpSync, mkdtempSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { check, type Report } from "../src/engine.js";
import { decide } from "../src/ledger.js";

const ROOT = resolve(".");
const N = 20000;

interface Scenario {
  id: string;
  program: string;
  stage: "first-draft" | "after-repair";
  stageLabel: string;
  report: Report;
  source: string;
}

function scratch(example: string, files: string[]): string {
  const dir = mkdtempSync(join(tmpdir(), `parity-${example}-`));
  for (const f of files) cpSync(join(ROOT, "examples", example, f), join(dir, f.split("/").pop()!));
  return dir;
}

const out: Scenario[] = [];

/* ---- INTEREST ---- */
{
  const src = readFileSync(join(ROOT, "examples/interest/interest.cbl"), "utf8");
  const first = check(join(ROOT, "examples/interest"), { n: N, seed: 1 });
  out.push({ id: "interest-1", program: "INTEREST", stage: "first-draft", stageLabel: "Careful Java translation", report: first, source: src });

  const dir = scratch("interest", ["interest.cbl", "faithful/InterestDecided.java"]);
  const contract = JSON.parse(readFileSync(join(ROOT, "examples/interest/parity.json"), "utf8"));
  contract.modern = {
    label: "Java 21 (after repair loop)",
    build: `javac -d .parity/build/modern ${join(ROOT, "java/Pic.java")} InterestDecided.java`,
    run: "java -cp .parity/build/modern InterestDecided",
  };
  writeFileSync(join(dir, "parity.json"), JSON.stringify(contract, null, 2));
  for (const f of first.findings.filter((x) => !x.derived)) {
    const accept = f.key === "O-NEW:sign-loss";
    decide(
      dir,
      "interest",
      f.key,
      accept ? "accept" : "preserve",
      accept
        ? "Legacy defect: negative balances were stored as credits. Correct it at cutover; affected accounts reconciled separately."
        : "Downstream settlement files depend on the legacy values. Reproduce exactly.",
      "Head of Retail Finance",
    );
  }
  const after = check(dir, { n: N, seed: 1 });
  out.push({ id: "interest-2", program: "INTEREST", stage: "after-repair", stageLabel: "After the repair loop", report: after, source: src });
}

/* ---- PAYROLL ---- */
{
  const src = readFileSync(join(ROOT, "examples/payroll/payroll.cbl"), "utf8");
  const first = check(join(ROOT, "examples/payroll"), { n: N, seed: 1 });
  out.push({ id: "payroll-1", program: "PAYROLL", stage: "first-draft", stageLabel: "Careful Java translation", report: first, source: src });

  const dir = scratch("payroll", ["payroll.cbl", "faithful/PayrollFaithful.java"]);
  const contract = JSON.parse(readFileSync(join(ROOT, "examples/payroll/parity.json"), "utf8"));
  contract.modern = {
    label: "Java 21 (after repair loop)",
    build: `javac -d .parity/build/modern ${join(ROOT, "java/Pic.java")} PayrollFaithful.java`,
    run: "java -cp .parity/build/modern PayrollFaithful",
  };
  writeFileSync(join(dir, "parity.json"), JSON.stringify(contract, null, 2));
  for (const f of first.findings.filter((x) => !x.derived)) {
    decide(
      dir,
      "payroll",
      f.key,
      "preserve",
      f.kind === "rounding"
        ? "Payslips must match the legacy system to the cent. Use COBOL rounding (half away from zero)."
        : "Reproduce legacy behaviour exactly; out-of-range handling to be revisited after cutover.",
      "Payroll Operations Lead",
    );
  }
  const after = check(dir, { n: N, seed: 1 });
  out.push({ id: "payroll-2", program: "PAYROLL", stage: "after-repair", stageLabel: "After the repair loop", report: after, source: src });
}

mkdirSync(join(ROOT, "dashboard/lib"), { recursive: true });
writeFileSync(
  join(ROOT, "dashboard/lib/data.ts"),
  `// GENERATED by scripts/gen-dashboard-data.ts from real Parity runs. Do not edit.\nimport type { Scenario } from "./types";\n\nexport const SCENARIOS: Scenario[] = ${JSON.stringify(out)};\n`,
);
for (const s of out) console.log(`${s.id.padEnd(11)} ${s.report.verdict.padEnd(34)} ${s.report.findings.length} findings  ${s.report.summary}`);
